---
title             : "Predicting Avocado Prices with Different Models"
shorttitle        : "Predicting Avocado Prices"
author: 
  - name          : "Rebecca Gordon"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    email         : "rebeccag@uoregon.edu"
affiliation:
  - id            : "1"
    institution   : "University of Oregon"
bibliography: references.bib
note: 
floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
documentclass     : "apa7"
classoption       : "man"
output            : papaja::apa6_pdf
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("papaja")
library(psych)
library(rpart)
library(finalfit)
library(tidyverse); theme_set(theme_minimal())
library(lubridate)
library(psych)
library(janitor)
library(caret)
library(kableExtra)
```


```{r}
avocado <- read_csv("avocado.csv")
avocado <- avocado %>% mutate(Date = ymd(Date))

avocado [,-1] %>% 
	describe() %>%
  kbl(caption = "Frequencies of the data", digits = 2) %>%
  kable_classic(full_width = F)



```
# References

---
nocite: '@*'
...